config/routes.rb
Rails.application.routes.draw do
  resources :alumnus
  resources :organizations
  resources :organizations
  resources :alumnus
  get 'pages/home'

  get 'pages/profil'

  resources :scholarship_successes
  resources :scholarship_registrations

  root 'pages#home'

end

app/models/scholarship_registration.rb
class ScholarshipRegistration < ActiveRecord::Base
end

app/controllers/scholarship_registrations_controller.rb
class ScholarshipRegistrationsController < ApplicationController
  before_action :set_scholarship_registration, only: [:show, :edit, :update, :destroy]

  # GET /scholarship_registrations
  # GET /scholarship_registrations.json
  def index
    @scholarship_registrations = ScholarshipRegistration.all
  end

  # GET /scholarship_registrations/1
  # GET /scholarship_registrations/1.json
  def show
  end

  # GET /scholarship_registrations/new
  def new
    @scholarship_registration = ScholarshipRegistration.new
  end

  # GET /scholarship_registrations/1/edit
  def edit
  end

  # POST /scholarship_registrations
  # POST /scholarship_registrations.json
  def create
    @scholarship_registration = ScholarshipRegistration.new(scholarship_registration_params)

    respond_to do |format|
      if @scholarship_registration.save
        format.html { redirect_to @scholarship_registration, notice: 'Scholarship registration was successfully created.' }
        format.json { render :show, status: :created, location: @scholarship_registration }
      else
        format.html { render :new }
        format.json { render json: @scholarship_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scholarship_registrations/1
  # PATCH/PUT /scholarship_registrations/1.json
  def update
    respond_to do |format|
      if @scholarship_registration.update(scholarship_registration_params)
        format.html { redirect_to @scholarship_registration, notice: 'Scholarship registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @scholarship_registration }
      else
        format.html { render :edit }
        format.json { render json: @scholarship_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholarship_registrations/1
  # DELETE /scholarship_registrations/1.json
  def destroy
    @scholarship_registration.destroy
    respond_to do |format|
      format.html { redirect_to scholarship_registrations_url, notice: 'Scholarship registration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scholarship_registration
      @scholarship_registration = ScholarshipRegistration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scholarship_registration_params
      params.require(:scholarship_registration).permit(:name, :address, :date_of_birth, :religion)
    end
end

app/helpers/scholarship_registrations_helper.rb
module ScholarshipRegistrationsHelper
end

app/views/scholarship_registrations/_form.html.erb
<%= simple_form_for(@scholarship_registration) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :date_of_birth %>
    <%= f.input :religion %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/scholarship_registrations/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <h3 class="lead">Edit Calon Beasiswa</h3>
      <%= render 'form' %>
      <%= link_to 'Show', @scholarship_registration %> |
      <%= link_to 'Index', scholarship_registrations_path, class: 'btn btn-standard' %>
    </div>
  </div>
</div>

app/views/scholarship_registrations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <h3 class="lead">Daftar Calon Peserta Beasiswa</h3>
      <br>
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th class="lead">Nama</th>
            <th class="lead">Alamat</th>
            <th class="lead">Tanggal Lahir</th>
            <th class="lead">Agama</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @scholarship_registrations.each do |scholarship_registration| %>
            <tr>
              <td><%= link_to scholarship_registration.name, scholarship_registration %></td>
              <td><%= scholarship_registration.address %></td>
              <td><%= scholarship_registration.date_of_birth %></td>
              <td><%= scholarship_registration.religion %></td>

              <td><%= link_to 'Edit', edit_scholarship_registration_path(scholarship_registration) %></td>
              <td><%= link_to 'Destroy', scholarship_registration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'Daftar Beasiswa', new_scholarship_registration_path, class: "btn btn-success-outline" %>

    </div>
  </div>
</div>

app/views/scholarship_registrations/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <h3 class="lead">Daftar Calon Beasiswa</h3>
      <%= render 'form' %>
      <%= link_to 'Index', scholarship_registrations_path, class: 'btn btn-standard' %>
    </div>
  </div>
</div>

app/views/scholarship_registrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scholarship_registration.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @scholarship_registration.address %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @scholarship_registration.date_of_birth %>
</p>

<p>
  <strong>Religion:</strong>
  <%= @scholarship_registration.religion %>
</p>

<%= link_to 'Edit', edit_scholarship_registration_path(@scholarship_registration) %> |
<%= link_to 'Back', scholarship_registrations_path %>