config/routes.rb
Rails.application.routes.draw do
  resources :alumnus
  resources :organizations
  resources :organizations
  resources :alumnus
  get 'pages/home'

  get 'pages/profil'

  resources :scholarship_successes
  resources :scholarship_registrations

  root 'pages#home'

end

app/controllers/scholarship_successes_controller.rb
class ScholarshipSuccessesController < ApplicationController
  before_action :set_scholarship_success, only: [:show, :edit, :update, :destroy]

  # GET /scholarship_successes
  # GET /scholarship_successes.json
  def index
    @scholarship_successes = ScholarshipSuccess.all
  end

  # GET /scholarship_successes/1
  # GET /scholarship_successes/1.json
  def show
  end

  # GET /scholarship_successes/new
  def new
    @scholarship_success = ScholarshipSuccess.new
  end

  # GET /scholarship_successes/1/edit
  def edit
  end

  # POST /scholarship_successes
  # POST /scholarship_successes.json
  def create
    @scholarship_success = ScholarshipSuccess.new(scholarship_success_params)

    respond_to do |format|
      if @scholarship_success.save
        format.html { redirect_to @scholarship_success, notice: 'Scholarship success was successfully created.' }
        format.json { render :show, status: :created, location: @scholarship_success }
      else
        format.html { render :new }
        format.json { render json: @scholarship_success.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scholarship_successes/1
  # PATCH/PUT /scholarship_successes/1.json
  def update
    respond_to do |format|
      if @scholarship_success.update(scholarship_success_params)
        format.html { redirect_to @scholarship_success, notice: 'Scholarship success was successfully updated.' }
        format.json { render :show, status: :ok, location: @scholarship_success }
      else
        format.html { render :edit }
        format.json { render json: @scholarship_success.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholarship_successes/1
  # DELETE /scholarship_successes/1.json
  def destroy
    @scholarship_success.destroy
    respond_to do |format|
      format.html { redirect_to scholarship_successes_url, notice: 'Scholarship success was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scholarship_success
      @scholarship_success = ScholarshipSuccess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scholarship_success_params
      params.require(:scholarship_success).permit(:name, :address, :date_of_birth, :religion)
    end
end

app/helpers/scholarship_successes_helper.rb
module ScholarshipSuccessesHelper
end

app/views/scholarship_successes/_form.html.erb
<%= simple_form_for(@scholarship_success) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :date_of_birth %>
    <%= f.input :religion %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/scholarship_successes/edit.html.erb
<h1>Editing Scholarship Success</h1>

<%= render 'form' %>

<%= link_to 'Show', @scholarship_success %> |
<%= link_to 'Back', scholarship_successes_path %>

app/views/scholarship_successes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scholarship Successes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Date of birth</th>
      <th>Religion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scholarship_successes.each do |scholarship_success| %>
      <tr>
        <td><%= scholarship_success.name %></td>
        <td><%= scholarship_success.address %></td>
        <td><%= scholarship_success.date_of_birth %></td>
        <td><%= scholarship_success.religion %></td>
        <td><%= link_to 'Show', scholarship_success %></td>
        <td><%= link_to 'Edit', edit_scholarship_success_path(scholarship_success) %></td>
        <td><%= link_to 'Destroy', scholarship_success, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scholarship success', new_scholarship_success_path %>

app/views/scholarship_successes/new.html.erb
<h1>New Scholarship Success</h1>

<%= render 'form' %>

<%= link_to 'Back', scholarship_successes_path %>

app/views/scholarship_successes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scholarship_success.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @scholarship_success.address %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @scholarship_success.date_of_birth %>
</p>

<p>
  <strong>Religion:</strong>
  <%= @scholarship_success.religion %>
</p>

<%= link_to 'Edit', edit_scholarship_success_path(@scholarship_success) %> |
<%= link_to 'Back', scholarship_successes_path %>