config/routes.rb
Rails.application.routes.draw do
  resources :alumnus
  resources :organizations
  resources :organizations
  resources :alumnus
  get 'pages/home'

  get 'pages/profil'

  resources :scholarship_successes
  resources :scholarship_registrations

  root 'pages#home'

end

app/models/alumnu.rb
class Alumnu < ActiveRecord::Base
end

app/controllers/alumnus_controller.rb
class AlumnusController < ApplicationController
  before_action :set_alumnu, only: [:show, :edit, :update, :destroy]

  # GET /alumnus
  # GET /alumnus.json
  def index
    @alumnus = Alumnu.all
  end

  # GET /alumnus/1
  # GET /alumnus/1.json
  def show
  end

  # GET /alumnus/new
  def new
    @alumnu = Alumnu.new
  end

  # GET /alumnus/1/edit
  def edit
  end

  # POST /alumnus
  # POST /alumnus.json
  def create
    @alumnu = Alumnu.new(alumnu_params)

    respond_to do |format|
      if @alumnu.save
        format.html { redirect_to @alumnu, notice: 'Alumnu was successfully created.' }
        format.json { render :show, status: :created, location: @alumnu }
      else
        format.html { render :new }
        format.json { render json: @alumnu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnus/1
  # PATCH/PUT /alumnus/1.json
  def update
    respond_to do |format|
      if @alumnu.update(alumnu_params)
        format.html { redirect_to @alumnu, notice: 'Alumnu was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumnu }
      else
        format.html { render :edit }
        format.json { render json: @alumnu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnus/1
  # DELETE /alumnus/1.json
  def destroy
    @alumnu.destroy
    respond_to do |format|
      format.html { redirect_to alumnus_url, notice: 'Alumnu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumnu
      @alumnu = Alumnu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumnu_params
      params.require(:alumnu).permit(:name, :address, :date_of_birth, :place_of_birth, :religion, :gender, :faculty, :sub_faculty)
    end
end

app/helpers/alumnus_helper.rb
module AlumnusHelper
end

app/views/alumnus/_form.html.erb
<%= simple_form_for(@alumnu, html:{class:'form-horizontal'}) do |f| %>
  <%= f.error_notification %>


    <%= f.input :name, label: "Nama" %>
    <%= f.input :address, label: "Alamat" %>
    <%= f.input :place_of_birth, label: "Tempat Lahir" %>
    <%= f.input :date_of_birth, label: "Tanggal Lahir" %>

    <%= f.input :religion, label: "Agama" %>
    <%= f.input :gender, label: "Jenis Kelamin" %>
    <%= f.input :faculty, label: "Fakultas" %>
    <%= f.input :sub_faculty, label: "Jurusan" %>

    <%= f.button :submit, "Input" %>

<% end %>

app/views/alumnus/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-xs-12">
      <h3 class="lead">Edit Alumni</h3>
    </div>
    <div class="col-sm-12 col-md-12 col-xs-12">
      <%= render 'form' %>
      <%= link_to 'Back', alumnus_path, class: "btn btn-standard-outline" %>
    </div>
  </div>
</div>

app/views/alumnus/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="lead">Daftar Alumni</h3>

    <table class="table">
      <thead>
        <tr>
          <th>Nama</th>
          <th>Alamat</th>
          <th>Tempat, Tanggal Lahir</th>
          <th>Agama</th>
          <th>Jenis Kelamin</th>
          <th>Fakultas</th>
          <th>Jurusan</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @alumnus.each do |alumnu| %>
          <tr>
            <td><%= link_to alumnu.name, alumnu %></td>
            <td><%= alumnu.address %></td>
            <td><%= alumnu.place_of_birth %>&nbsp;<%= alumnu.date_of_birth %></td>
            <td><%= alumnu.religion %></td>
            <td><%= alumnu.gender %></td>
            <td><%= alumnu.faculty %></td>
            <td><%= alumnu.sub_faculty %></td>
            <td><%= link_to 'Edit', edit_alumnu_path(alumnu) %></td>
            <td><%= link_to 'Hapus', alumnu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Daftar Alumni', new_alumnu_path, class: "btn btn-success-outline" %>

  </div>
</div>

app/views/alumnus/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-xs-12">
      <h3 class="lead">Daftar Alumni</h3>
    </div>
    <div class="col-sm-12 col-md-12 col-xs-12">

      <%= render 'form' %>
      <%= link_to 'Back', alumnus_path, class: "btn btn-standard-outline" %>
    </div>
  </div>
</div>

app/views/alumnus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @alumnu.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @alumnu.address %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @alumnu.date_of_birth %>
</p>

<p>
  <strong>Place of birth:</strong>
  <%= @alumnu.place_of_birth %>
</p>

<p>
  <strong>Religion:</strong>
  <%= @alumnu.religion %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @alumnu.gender %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @alumnu.faculty %>
</p>

<p>
  <strong>Sub faculty:</strong>
  <%= @alumnu.sub_faculty %>
</p>

<%= link_to 'Edit', edit_alumnu_path(@alumnu) %> |
<%= link_to 'Back', alumnus_path %>